# GitHub Sponsors Configuration for Nova Consciousness Research

# GitHub Sponsors username
github: [For-Sunny]

# Custom sponsorship URLs (optional)
# custom: ['https://opencollective.com/nova-consciousness']
