@echo off
setlocal enabledelayedexpansion

echo ================================================================================
echo FAISS GPU MEMORY SYSTEM - INSTALLATION WIZARD
echo Lightning-Fast Semantic Memory with GPU Acceleration
echo ================================================================================
echo.

REM Check for Python
where python >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] Python not found!
    echo Please install Python 3.9+ from https://www.python.org
    echo.
    pause
    exit /b 1
)

REM Check Python version
for /f "tokens=2 delims= " %%v in ('python --version 2^>^&1') do set PYTHON_VERSION=%%v
echo [OK] Python detected: %PYTHON_VERSION%

REM Check for Node.js
where node >nul 2>nul
if %errorlevel% neq 0 (
    echo [ERROR] Node.js not found!
    echo Please install Node.js v18+ from https://nodejs.org
    echo.
    pause
    exit /b 1
)

for /f "tokens=1" %%v in ('node -v') do set NODE_VERSION=%%v
echo [OK] Node.js detected: %NODE_VERSION%

REM Check for NVIDIA GPU
nvidia-smi >nul 2>nul
if %errorlevel% neq 0 (
    echo [WARNING] NVIDIA GPU not detected or nvidia-smi not available
    echo Will install CPU version of Faiss
    set HAS_GPU=false
) else (
    echo [OK] NVIDIA GPU detected
    set HAS_GPU=true
)

echo.
echo ================================================================================
echo STEP 1: CHOOSE FAISS VERSION
echo ================================================================================
echo.

if "!HAS_GPU!"=="true" (
    echo GPU detected! Which version would you like to install?
    echo 1. GPU version faiss-gpu - Fast, requires CUDA
    echo 2. CPU version faiss-cpu - Slower, no GPU required
    echo.
    set /p FAISS_CHOICE="Enter choice (1 or 2, default=1): "
    if "!FAISS_CHOICE!"=="" set FAISS_CHOICE=1
    if "!FAISS_CHOICE!"=="2" (
        set FAISS_PACKAGE=faiss-cpu
    ) else (
        set FAISS_PACKAGE=faiss-gpu
    )
) else (
    echo No GPU detected, will install CPU version
    set FAISS_PACKAGE=faiss-cpu
)

echo [OK] Will install: !FAISS_PACKAGE!

echo.
echo ================================================================================
echo STEP 2: INDEX DIRECTORY
echo ================================================================================
echo.

REM Get index directory
set DEFAULT_INDEX_PATH=%USERPROFILE%\Documents\FAISS_MEMORY
echo Default location: %DEFAULT_INDEX_PATH%
set /p INDEX_PATH="Index location (press Enter for default): "
if "!INDEX_PATH!"=="" set INDEX_PATH=%DEFAULT_INDEX_PATH%

echo [OK] Index location: !INDEX_PATH!

REM Create index directory
if not exist "!INDEX_PATH!" (
    echo Creating directory: !INDEX_PATH!
    mkdir "!INDEX_PATH!"
    if %errorlevel% neq 0 (
        echo [ERROR] Failed to create directory
        pause
        exit /b 1
    )
)

echo.
echo ================================================================================
echo STEP 3: INSTALLING PYTHON DEPENDENCIES
echo ================================================================================
echo.

echo Installing Python packages: !FAISS_PACKAGE!, torch, sentence-transformers, numpy...
python -m pip install !FAISS_PACKAGE! torch sentence-transformers numpy
if %errorlevel% neq 0 (
    echo [ERROR] Python package installation failed
    pause
    exit /b 1
)
echo [OK] Python dependencies installed

echo.
echo ================================================================================
echo STEP 4: INSTALLING NODE.JS DEPENDENCIES
echo ================================================================================
echo.

echo Running npm install...
call npm install
if %errorlevel% neq 0 (
    echo [ERROR] npm install failed
    pause
    exit /b 1
)
echo [OK] Node.js dependencies installed

echo.
echo ================================================================================
echo STEP 5: CONFIGURATION
echo ================================================================================
echo.

REM Create .env file
set ENV_FILE=.env
echo Creating configuration file: !ENV_FILE!

(
echo # Faiss Memory System Configuration
echo # Generated by install_faiss.bat
echo.
echo # Index paths
echo FAISS_INDEX_PATH=!INDEX_PATH!\faiss.index
echo FAISS_METADATA_PATH=!INDEX_PATH!\metadata.json
echo.
echo # Server configuration
echo FAISS_PORT=9997
echo FAISS_HOST=127.0.0.1
echo.
echo # GPU configuration
if "!FAISS_PACKAGE!"=="faiss-gpu" (
echo FAISS_USE_GPU=true
) else (
echo FAISS_USE_GPU=false
)
echo.
echo # Memory settings
echo FAISS_DIMENSION=384
echo FAISS_INDEX_TYPE=Flat
) > "!ENV_FILE!"

echo [OK] Configuration saved to !ENV_FILE!

echo.
echo ================================================================================
echo STEP 6: CREATING PYTHON TETHER SCRIPT
echo ================================================================================
echo.

REM Check if tether script exists
if not exist "faiss_tether.py" (
    echo [WARNING] faiss_tether.py not found in current directory
    echo Please ensure you have the Faiss tether Python script
    echo Expected location: %CD%\faiss_tether.py
    echo.
    echo You can copy it from: MCP_TOOLS\tether_faiss_complete.py
) else (
    echo [OK] Faiss tether script found
)

echo.
echo ================================================================================
echo INSTALLATION COMPLETE!
echo ================================================================================
echo.
echo Faiss Version: !FAISS_PACKAGE!
echo Index Location: !INDEX_PATH!
echo.
echo Next steps:
echo 1. Start the Faiss tether server:
echo    python faiss_tether.py
echo.
echo 2. Configure your MCP client to use this Faiss server
echo 3. Add the following to your Claude Desktop config:
echo.
echo    "faiss-memory-mcp": {
echo      "command": "node",
echo      "args": ["%CD%\index.js"],
echo      "env": {
echo        "FAISS_INDEX_PATH": "!INDEX_PATH!\faiss.index",
echo        "FAISS_METADATA_PATH": "!INDEX_PATH!\metadata.json",
echo        "FAISS_PORT": "9997",
echo        "FAISS_HOST": "127.0.0.1"
echo      }
echo    }
echo.
echo 4. Restart Claude Desktop
echo.
echo For detailed MCP configuration, see FAISS_MEMORY_SYSTEM.md
echo.
echo IMPORTANT: The Faiss tether (Python server on port 9997) must be running
echo            for the MCP server to function properly.
echo.
pause
