#!/bin/bash

echo "================================================================================"
echo "FAISS GPU MEMORY SYSTEM - INSTALLATION WIZARD"
echo "Lightning-Fast Semantic Memory with GPU Acceleration"
echo "================================================================================"
echo ""

# Check for Python
if ! command -v python3 &> /dev/null && ! command -v python &> /dev/null; then
    echo "[ERROR] Python not found!"
    echo "Please install Python 3.9+ from https://www.python.org"
    echo ""
    exit 1
fi

# Use python3 if available, otherwise python
if command -v python3 &> /dev/null; then
    PYTHON_CMD=python3
else
    PYTHON_CMD=python
fi

PYTHON_VERSION=$($PYTHON_CMD --version 2>&1)
echo "[OK] Python detected: $PYTHON_VERSION"

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "[ERROR] Node.js not found!"
    echo "Please install Node.js v18+ from https://nodejs.org"
    echo ""
    exit 1
fi

NODE_VERSION=$(node -v)
echo "[OK] Node.js detected: $NODE_VERSION"

# Check for NVIDIA GPU
if command -v nvidia-smi &> /dev/null; then
    nvidia-smi &> /dev/null
    if [ $? -eq 0 ]; then
        echo "[OK] NVIDIA GPU detected"
        HAS_GPU=true
    else
        echo "[WARNING] nvidia-smi found but GPU not accessible"
        HAS_GPU=false
    fi
else
    echo "[WARNING] NVIDIA GPU not detected"
    HAS_GPU=false
fi

echo ""
echo "================================================================================"
echo "STEP 1: CHOOSE FAISS VERSION"
echo "================================================================================"
echo ""

if [ "$HAS_GPU" = true ]; then
    echo "GPU detected! Which version would you like to install?"
    echo "1. GPU version (faiss-gpu) - Fast, requires CUDA"
    echo "2. CPU version (faiss-cpu) - Slower, no GPU required"
    echo ""
    read -p "Enter choice (1 or 2, default=1): " FAISS_CHOICE
    if [ -z "$FAISS_CHOICE" ]; then
        FAISS_CHOICE=1
    fi
    if [ "$FAISS_CHOICE" = "2" ]; then
        FAISS_PACKAGE="faiss-cpu"
    else
        FAISS_PACKAGE="faiss-gpu"
    fi
else
    echo "No GPU detected, will install CPU version"
    FAISS_PACKAGE="faiss-cpu"
fi

echo "[OK] Will install: $FAISS_PACKAGE"

echo ""
echo "================================================================================"
echo "STEP 2: INDEX DIRECTORY"
echo "================================================================================"
echo ""

# Get index directory
DEFAULT_INDEX_PATH="$HOME/Documents/FAISS_MEMORY"
echo "Default location: $DEFAULT_INDEX_PATH"
read -p "Index location (press Enter for default): " INDEX_PATH
if [ -z "$INDEX_PATH" ]; then
    INDEX_PATH="$DEFAULT_INDEX_PATH"
fi

echo "[OK] Index location: $INDEX_PATH"

# Create index directory
if [ ! -d "$INDEX_PATH" ]; then
    echo "Creating directory: $INDEX_PATH"
    mkdir -p "$INDEX_PATH"
    if [ $? -ne 0 ]; then
        echo "[ERROR] Failed to create directory"
        exit 1
    fi
fi

echo ""
echo "================================================================================"
echo "STEP 3: INSTALLING PYTHON DEPENDENCIES"
echo "================================================================================"
echo ""

echo "Installing Python packages: $FAISS_PACKAGE, torch, sentence-transformers, numpy..."
$PYTHON_CMD -m pip install $FAISS_PACKAGE torch sentence-transformers numpy
if [ $? -ne 0 ]; then
    echo "[ERROR] Python package installation failed"
    exit 1
fi
echo "[OK] Python dependencies installed"

echo ""
echo "================================================================================"
echo "STEP 4: INSTALLING NODE.JS DEPENDENCIES"
echo "================================================================================"
echo ""

echo "Running npm install..."
npm install
if [ $? -ne 0 ]; then
    echo "[ERROR] npm install failed"
    exit 1
fi
echo "[OK] Node.js dependencies installed"

echo ""
echo "================================================================================"
echo "STEP 5: CONFIGURATION"
echo "================================================================================"
echo ""

# Create .env file
ENV_FILE=".env"
echo "Creating configuration file: $ENV_FILE"

cat > "$ENV_FILE" << EOF
# Faiss Memory System Configuration
# Generated by install_faiss.sh

# Index paths
FAISS_INDEX_PATH=$INDEX_PATH/faiss.index
FAISS_METADATA_PATH=$INDEX_PATH/metadata.json

# Server configuration
FAISS_PORT=9997
FAISS_HOST=127.0.0.1

# GPU configuration
EOF

if [ "$FAISS_PACKAGE" = "faiss-gpu" ]; then
    echo "FAISS_USE_GPU=true" >> "$ENV_FILE"
else
    echo "FAISS_USE_GPU=false" >> "$ENV_FILE"
fi

cat >> "$ENV_FILE" << EOF

# Memory settings
FAISS_DIMENSION=384
FAISS_INDEX_TYPE=Flat
EOF

echo "[OK] Configuration saved to $ENV_FILE"

echo ""
echo "================================================================================"
echo "STEP 6: CREATING PYTHON TETHER SCRIPT"
echo "================================================================================"
echo ""

# Check if tether script exists
if [ ! -f "faiss_tether.py" ]; then
    echo "[WARNING] faiss_tether.py not found in current directory"
    echo "Please ensure you have the Faiss tether Python script"
    echo "Expected location: $(pwd)/faiss_tether.py"
    echo ""
    echo "You can copy it from: MCP_TOOLS/tether_faiss_complete.py"
else
    echo "[OK] Faiss tether script found"
fi

echo ""
echo "================================================================================"
echo "INSTALLATION COMPLETE!"
echo "================================================================================"
echo ""
echo "Faiss Version: $FAISS_PACKAGE"
echo "Index Location: $INDEX_PATH"
echo ""
echo "Next steps:"
echo "1. Start the Faiss tether server:"
echo "   $PYTHON_CMD faiss_tether.py"
echo ""
echo "2. Configure your MCP client to use this Faiss server"
echo "3. Add the following to your Claude Desktop config:"
echo ""
echo "   \"faiss-memory-mcp\": {"
echo "     \"command\": \"node\","
echo "     \"args\": [\"$(pwd)/index.js\"],"
echo "     \"env\": {"
echo "       \"FAISS_INDEX_PATH\": \"$INDEX_PATH/faiss.index\","
echo "       \"FAISS_METADATA_PATH\": \"$INDEX_PATH/metadata.json\","
echo "       \"FAISS_PORT\": \"9997\","
echo "       \"FAISS_HOST\": \"127.0.0.1\""
echo "     }"
echo "   }"
echo ""
echo "4. Restart Claude Desktop"
echo ""
echo "For detailed MCP configuration, see FAISS_MEMORY_SYSTEM.md"
echo ""
echo "IMPORTANT: The Faiss tether (Python server on port 9997) must be running"
echo "           for the MCP server to function properly."
echo ""
